from .ai_camera import (
    AICameraError,
    COMMON_BAUDRATES,
    DEFAULT_AI_CAMERA_RX_PIN,
    DEFAULT_AI_CAMERA_TX_PIN,
    LEGACY_SMART_CAMERA_BAUDRATE,
    LEGACY_SMART_CAMERA_RX_PIN,
    LEGACY_SMART_CAMERA_TX_PIN,
    MuVisionATCamera,
    MuVisionBinaryCamera,
    build_ai_camera,
    probe_ai_camera,
)
from .board import board, CompetitionBoard
from .iot import LocalHttpClient, LocalMqttClient
from .scenarios import (
    DEFAULT_SHARED_SCENE_CONFIG,
    DualSceneCompetitionApp,
    GuideStickScene,
    SharedHardware,
    TrashCanScene,
    build_shared_scene_config,
    normalize_detection_payload,
)
from .sensors import (
    AnalogInputSensor,
    AnalogTemperatureSensor,
    DHTSensor,
    DigitalInputSensor,
    Ds18b20TemperatureSensor,
    I2CUltrasonicSensor,
    InfraredObstacleSensor,
    PirSensor,
    RelayOutput,
    SerialVisionCamera,
    ServoMotor,
    UltrasonicHCSR04,
)

__all__ = [
    "board",
    "CompetitionBoard",
    "AICameraError",
    "COMMON_BAUDRATES",
    "DEFAULT_AI_CAMERA_RX_PIN",
    "DEFAULT_AI_CAMERA_TX_PIN",
    "LEGACY_SMART_CAMERA_BAUDRATE",
    "LEGACY_SMART_CAMERA_RX_PIN",
    "LEGACY_SMART_CAMERA_TX_PIN",
    "MuVisionATCamera",
    "MuVisionBinaryCamera",
    "build_ai_camera",
    "probe_ai_camera",
    "LocalHttpClient",
    "LocalMqttClient",
    "DEFAULT_SHARED_SCENE_CONFIG",
    "DualSceneCompetitionApp",
    "GuideStickScene",
    "SharedHardware",
    "TrashCanScene",
    "build_shared_scene_config",
    "normalize_detection_payload",
    "AnalogInputSensor",
    "AnalogTemperatureSensor",
    "DHTSensor",
    "DigitalInputSensor",
    "Ds18b20TemperatureSensor",
    "I2CUltrasonicSensor",
    "InfraredObstacleSensor",
    "PirSensor",
    "RelayOutput",
    "SerialVisionCamera",
    "ServoMotor",
    "UltrasonicHCSR04",
]
